name: One-click Provisioning
on:
  workflow_dispatch:
    inputs:
      Target:
        description: 'Resource you want to provision'
        required: true
        default: NETWORK
        type: choice
        options:
        - BACKEND
        - DATABASE
        - FRONTEND
        - NETWORK
      applyChanges:
        description: 'Check the box to apply changes'
        required: true
        type: boolean
      environment:
        description: 'Environment to Provision Infra'
        required: true
        type: choice
        default: test
        options:
        - test
        - dev
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  S3test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name:  Provision resource
        run: |
          if [ ${{ inputs.applyChanges }} == true ];
          then
            make ENV=${{ inputs.environment }} target=${{ inputs.Target }} apply
          else
            make ENV=${{ inputs.environment }} target=${{ inputs.Target }} plan
          fi
